table Orders
	lineageTag: fd95df31-46f2-4f7f-b760-c06b56cc7c26

	measure 'Total Sales' = sum(Orders[Sales])
		lineageTag: 5019b6d9-b980-4e52-b114-69afa9c42ac2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = sum(Orders[Profit])
		lineageTag: 5f2e2e56-4253-4a47-bcb2-7695ffbd5738

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 11ce39e6-8249-4927-95e7-bd88c30e6255
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b83f0c57-e9bb-4b13-8338-38bde90c4a88
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d6ebeb21-c4fa-43df-b3e3-df9797fa7ccd
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: cb4ad343-82b2-4502-bcd1-f432e59363a4
			defaultHierarchy: LocalDateTable_94f3b05e-dd4a-4784-8a45-d2094c69d29c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fdceee35-7f0e-463b-b05a-078cedcf26d7
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 52507d99-13de-4839-a505-5393a854c998
			defaultHierarchy: LocalDateTable_3d90fe04-3364-4375-8ad7-fb8c609ffcf2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: dc6bb869-0fcc-4c50-8a9a-0f628c241cf8
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 3a6ad0af-631d-42e3-b603-c7ab65e188bd
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 63b9ba1b-6068-46fb-b7c8-518d84d7c4a2
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e92da6f7-6dd9-403b-b949-04a7cd6eac89
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 948e5825-c3e9-4a3d-a89f-5ccfffbe0916
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d371331a-1dc5-496d-9d75-b8b9bbef72c5
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 4f01c176-bc84-4276-9101-dbda5eed71c8
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 15f9e9d2-73d4-4c50-b1c4-e85401a963a1
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a704134a-49cb-4767-ae68-e1e1e9321e82
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 09eb29ce-36a3-4019-8ffb-f18742bb8bab
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6b944091-387c-4fc8-92fb-f65f84a3995c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 7afd7893-07b9-4406-8507-5950cfbfc2ce
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 86496c52-b0f2-4c92-8126-027b140cfd22
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 2accad7b-0390-43b1-8d0d-e31cfca6243d
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 472b8145-7a89-455a-a360-535280990656
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: b0b0ebc5-f7f6-4ec1-8a6f-5ae1a6301b31
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: f18e7703-9ebf-4cfd-900d-3bd82467b7fe
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Downloads\sample_superstore (1).xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

